version: '3'
services:
  generator:
    build: .
    image: noesysmobile/cb-large-dataset-generator:0.1.0
    env_file:
    - .env
    volumes:
      - type: bind
        source: ${PWD}/LargeDatasetGenerator/example.json
        target: /template/DocTemplate.json